#ifndef JOBPOSITION_H
#define JOBPOSITION_H

enum companyPosition{
    CEO, 
    CFO, 
    CIO, 
    OPERATIONS_MANAGER, 
    OPERATIONS_SUPERVISOR, 
    OPERATIONS_ASSOCIATE, 
    HR_MANAGER, 
    HR_SUPERVISOR, 
    HR_ASSISTANT, 
    CUSTOMER_SERVICE, 
    CUSTOMER_SERVICE_MANAGER, 
    CUSTOMER_SERVICE_SUPERVISOR, 
    LAWYER, 
    LITIGATOR, 
    LAW_CLERK
};

#endif
